// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyHvdFpRJks0SLCh9qc8BxQeoqaobynQ',
    appId: '1:569426499692:web:4d460b962728c55d2aa049',
    messagingSenderId: '569426499692',
    projectId: 'smartagro-connect',
    authDomain: 'smartagro-connect.firebaseapp.com',
    storageBucket: 'smartagro-connect.firebasestorage.app',
    measurementId: 'G-MLCFDPWKJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmzMNhU2nfPkHXmIP6S_xTMeJ5LupTEg',
    appId: '1:569426499692:android:9dbe9f2f4912a28b2aa049',
    messagingSenderId: '569426499692',
    projectId: 'smartagro-connect',
    storageBucket: 'smartagro-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7UuW8R9dx6Y-qM1OfTNA1Ybh-hoWLQA',
    appId: '1:569426499692:ios:a4134723eeaef80f2aa049',
    messagingSenderId: '569426499692',
    projectId: 'smartagro-connect',
    storageBucket: 'smartagro-connect.firebasestorage.app',
    androidClientId: '569426499692-r1o1mc7872khq9u3urg45vqbtl9oo7tk.apps.googleusercontent.com',
    iosClientId: '569426499692-jv12q31lkshj3bs86kd6c5jsll1skb0o.apps.googleusercontent.com',
    iosBundleId: 'c',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwyHvdFpRJks0SLCh9qc8BxQeoqaobynQ',
    appId: '1:569426499692:web:9912290d671cbcb72aa049',
    messagingSenderId: '569426499692',
    projectId: 'smartagro-connect',
    authDomain: 'smartagro-connect.firebaseapp.com',
    storageBucket: 'smartagro-connect.firebasestorage.app',
    measurementId: 'G-8PDX53GWTS',
  );
}
